actions/16/dialog-cancel.svg
actions/16/dialog-close.svg
actions/16/dialog-no.svg
actions/48/dialog-cancel.svg
actions/48/dialog-close.svg
actions/48/dialog-no.svg

As far as I know, these are basically vestiges from the days when dialog buttons had icons. Pretty sure it's safe to drop them

drop dialog-close/cancel/no

---

status/48/battery-full-charged.svg
status/48/battery-full-charging.svg
status/48/battery-full.svg

This updates the icons to match with the symbolic variants:
* No lightning on the full-charged state
* Don't change hue for the full and full-charging states

Match 48px color batteries with symbolic

---

mimes/128/audio-x-generic.svg
mimes/16/audio-x-generic.svg
mimes/24/audio-x-generic.svg
mimes/32/audio-x-generic.svg
mimes/48/audio-x-generic.svg
mimes/64/audio-x-generic.svg

Proposing for feedback
My thinking is that the current audio mime leans heavily towards music, but we can't know the contents of the audio file. So it might be better to use a mime that more conveys raw audio than music specifically

make audio-x-generic more generic

---

actions/128/process-stop.svg
actions/16/process-stop.svg
actions/24/process-stop.svg
actions/32/process-stop.svg
actions/48/process-stop.svg
actions/64/process-stop.svg

redesign `process-stop` in all sizes using colors from our new palette and with a rounded cross matching the symbolic icon

Redo color process-stop icons

---

status/symbolic/dialog-warning-symbolic.svg

The outline is just too hard to see for yellow. Filled seems to look nicer

dialog-warning-symbolic: filled instead of outline

---

mimes/64/audio-x-generic-symbolic.svg

It looks like `-gtk-icontheme` will only grab icons at sizes we provide and won't stretch (which is great). This adds a 64px version of this icon so that it has more sizes available and we go from this (see sidebar):
to this

64px audio-x-generic-symbolic

---

mimes/128/x-office-presentation-rtl.svg
mimes/128/x-office-presentation-template-rtl.svg
mimes/128/x-office-presentation-template.svg
mimes/128/x-office-presentation.svg
mimes/16/x-office-presentation-rtl.svg
mimes/16/x-office-presentation-template-rtl.svg
mimes/16/x-office-presentation-template.svg
mimes/16/x-office-presentation.svg
mimes/24/x-office-presentation-rtl.svg
mimes/24/x-office-presentation-template-rtl.svg
mimes/24/x-office-presentation-template.svg
mimes/24/x-office-presentation.svg
mimes/32/x-office-presentation-rtl.svg
mimes/32/x-office-presentation-template-rtl.svg
mimes/32/x-office-presentation-template.svg
mimes/32/x-office-presentation.svg
mimes/48/x-office-presentation-rtl.svg
mimes/48/x-office-presentation-template-rtl.svg
mimes/48/x-office-presentation-template.svg
mimes/48/x-office-presentation.svg
mimes/64/x-office-presentation-rtl.svg
mimes/64/x-office-presentation-template-rtl.svg
mimes/64/x-office-presentation-template.svg
mimes/64/x-office-presentation.svg

I moved the baselines to match those in the HIG and cleaned up a bit. As the baselines go I checked with other icons and the changing the baseline does't seem to throw off the x-height. It appears to match up with the shorter icons like video-player or video-x-generic.

Fix baselines and clean up presentation mimes

---

status/16/channel-secure.svg
status/16/locked.svg
status/24/channel-secure.svg
status/24/locked.svg
status/32/channel-secure.svg
status/32/locked.svg
status/48/channel-secure.svg
status/48/locked.svg

To go along with `channel-secure-symbolic`
original icons are vacuumed by the pre-commit hook. No other changes

Add links for channel-secure

---

devices/16/drive-harddisk.svg
devices/24/drive-harddisk.svg
devices/32/drive-harddisk.svg
devices/48/drive-harddisk.svg

The harddisk icons were drawn many eons ago and don't obey our rules about highlights etc. This takes the detail stuff and plops it on top of `drive-removable-media` which does follow the rules

Rebase harddisk on removable media

---

status/symbolic/check-active-symbolic.svg
status/symbolic/check-mixed-symbolic.svg

Adds some explicitly named check icons so that we:
* Don't abuse other icon names when what we want is "check" and not "apply" or some other
* Allow us to use symbolic icons in the stylesheet for checkboxes

Add explicitly named check icons

---

debian/postinst
debian/preinst
debian/prerm
debian/triggers

Fixes #433
The code is largely copy-pasted from `gnome-icon-theme` packaging
Includes PR #434 because otherwise they would conflict. And apparently github cannot handle dependent PRs, so the displayed diff includes changes from both
Supersedes #435 where I've accidentally messed up git history

Enable icons cache

---

mimes/16/application-msword.svg
mimes/16/application-vnd.ms-access.svg
mimes/16/application-vnd.ms-excel.svg
mimes/16/application-vnd.ms-powerpoint.presentation.macroEnabled.12.svg
mimes/16/application-vnd.ms-powerpoint.svg
mimes/16/application-vnd.openxmlformats-officedocument.spreadsheetml.sheet.svg

Currently there are no 16px versions of those icons. I know the 24px svgs can be scaled down, but this proposal contains slightly optimized icons for 16px (mostly aligning along the grid).
I've added these to elementary-xfce anyway, so I thought I'd propose them here too.

Add 16px variants of MS Office icons

---

status/24/error.svg

Seems vestigial. it's not in the spec. `dialog-error` is the spec named version

Remove error symlink

---

mimes/128/font-x-generic.svg
mimes/16/font-x-generic.svg
mimes/24/font-x-generic.svg
mimes/32/font-x-generic.svg
mimes/48/font-x-generic.svg
mimes/64/font-x-generic.svg

A redesign for font-x-generic to fit in with the other mimetypes:

Redesign font-x-generic

---

mimes/128/application-sql.svg
mimes/16/application-sql.svg
mimes/24/application-sql.svg
mimes/32/application-sql.svg
mimes/32/office-database.svg
mimes/48/application-sql.svg
mimes/48/office-database.svg
mimes/64/application-sql.svg

Fixes #375 
The mime-type name for .sql files is `application/sql`:
https://cgit.freedesktop.org/xdg/shared-mime-info/tree/freedesktop.org.xml.in#n6251

mimes: add symbolic links for sql files

---

actions/symbolic/system-reboot-symbolic.svg

Just symlink the icon we're using in the installer for now. Minimally fixes #616

Symlink system-reboot-symbolic

---

pre-commit

The pre-commit will not vacuum if you're using flatpak-ed inkscape (like me) so I added lines to check which is installed and use the appropriate command.

updated pre-commit to check for flatpak inkscape

---

actions/16/selection-bottom.svg
actions/16/selection-lower.svg
actions/16/selection-raise.svg
actions/16/selection-top.svg
actions/24/selection-bottom.svg
actions/24/selection-lower.svg
actions/24/selection-raise.svg
actions/24/selection-top.svg
actions/symbolic/selection-bottom-symbolic.svg
actions/symbolic/selection-lower-symbolic.svg
actions/symbolic/selection-raise-symbolic.svg
actions/symbolic/selection-top-symbolic.svg

Fixes #642 
The color scheme was chosen to match object-flip

Add selection-foo z axis icons

---

actions/symbolic/edit-delete-symbolic.svg

The filled style feels very heavy when we're trying to use this icon in lists or with other much lighter icons. This makes it so we can use the filled style for `user-trash` when we need the heaver icon, but we have a line style with `edit-delete` when we need a lighter version

Make edit-trash in line style

---

README.md

For convenience :)
If this change is welcome, I'll also add the same links in CONTRIBUTING.md (although perhaps it would be better to remove that file since it pretty much duplicates the README?)

README: add links to the color palette

---

actions/24/document-print-preview.svg
actions/32/document-print-preview.svg
actions/48/document-print-preview.svg

New colored versions of document-print-preview.
Fixes #535.
Looks like this:

Make new colored icons for print preview

---

actions/16/call-end.svg
actions/16/call-stop.svg

Made an icon for the call-stop spec.
Fixes #534.
**NOTE:** neither call-stop or call-start have icons above 16px size.
Looks like this:

Made a colored call-stop & call-end icon

---

status/16/night-light-disabled-symbolic.svg
status/16/night-light-symbolic.svg

Not sure if you even care about 16px versions of the symbolic status icons you have in 24 now. However I wanted/needed one for night-light (I also want to use the icon in the xfce panel, which can have 16px symbolic icons) so I created it.
If you generally want this icon, I can also create the missing files night-light-disabled-[10..90]-symbolic.svg

Add 16px night-light icons

---

mimes/128/application-x-generic.svg
mimes/16/application-x-generic.svg
mimes/24/application-x-generic.svg
mimes/32/application-x-generic.svg
mimes/48/application-x-generic.svg
mimes/64/application-x-generic.svg

It looks like GLib.FileInfo returns this icon as a fallback for mimetype icons, so we need to have it

Add missing application-x-generic

---

meson/symlink.py

Fixes #832
Note that when using python's argparse library, non-optional arguments are usually only positional, not with keywords, which would make the whole "take the only item of a list of one" thing unnecessary (and fix some edge cases, where `--src 1 --src 2` is accepted but only stores `2`), but I didn't want to rewrite the whole script just to make it "idiomatic python".

meson/symlink: create relative symlinks instead of absolute ones

---

actions/24/draw-calligraphic.svg

Fixes #714 
This is how the icon look in elementary OS light theme
This is how the icon look in elementary OS dark theme
There's another layer there that contains things I've used in the process of designing this. I'll be cleaning them up once this is finalized and approved.

Add Inkscape's Calligraphy Tool

---

actions/symbolic/pan-down-symbolic.svg
actions/symbolic/pan-end-symbolic.svg
actions/symbolic/pan-start-symbolic.svg
actions/symbolic/pan-up-symbolic.svg

Uses the same consistent arrow head shape as the new `go` icons

Round symbolic pan-* icons

---

actions/16/edit-copy.svg
actions/16/edit-paste.svg
actions/24/edit-copy.svg
actions/24/edit-paste.svg
actions/32/edit-copy.svg
actions/32/edit-paste.svg
actions/48/edit-copy.svg
actions/48/edit-paste.svg
data/icons.appdata.xml.in

Symbolic versions don't have an arrow and they seem still to convey their meaning. Also helps reduce noise in uses like: https://github.com/elementary/terminal/pull/639
And saves me having to update an arrow shape yay lol

Actions: Remove arrows from Copy and Paste

---

mimes/128/application-vnd.openofficeorg.extension.svg
mimes/128/extension.svg
mimes/128/libpeas-plugin.svg

Adds extension mimetype and related symlinks at 128px.
Addresses part of issue #548

Add extension mimetype at 128px

---

mimes/16/text-x-vala.svg

Fixes #836 
Hope I'm not bothering with too many PRs! Just trying to pick something off of the issue tracker every few days.
Using the screenshot in the issue above, I edited mine as the MainWindow.vala icon just to compare it to the current downscaled version.
Let me know if this needs any tweaking. Thanks!

Add Vala mimetype at 16px

---

places/128/folder-download-open.svg
places/128/folder-download.svg
places/32/folder-download-open.svg
places/32/folder-download.svg
places/48/folder-download-open.svg
places/48/folder-download.svg
places/64/folder-download-open.svg
places/64/folder-download.svg

Updated the places folder-download folders to use the rounded arrow style. Tried to also make the smaller sizes a little more legible and consistent while I was at it.
---
Current:
Proposed:

Use rounded arrow on download folder

---

mimes/meson.build

If you disable thumbnails, you can verify that this is actually the correct icon name and it was broken before

FileTypes: Fix incorrect SVG symlink

---

apps/128/application-default-icon.svg
apps/16/application-default-icon.svg
apps/24/application-default-icon.svg
apps/32/application-default-icon.svg
apps/48/application-default-icon.svg
apps/64/application-default-icon.svg

The application-default-icon redesign from #1076 with the more rounded square and using a different metaphor and color

Apps: redesign application-default-icon

---

status/48/microphone-sensitivity-muted-symbolic.svg
status/symbolic/microphone-sensitivity-muted-symbolic.svg

We actually do still need this for system mic level notifications

Status: re-add muted mic symbolics

---

actions/16/browser-download.svg
actions/24/browser-download.svg
actions/32/browser-download.svg
actions/48/browser-download.svg

Completes part of Issue #922 (Make all of the arrows consistent)

Actions: Use rounded arrow for browser-download

---

actions/16/document-page-setup.svg
actions/16/edit-copy.svg
actions/16/edit-cut.svg
actions/24/edit-cut.svg
actions/32/document-page-setup.svg
actions/32/edit-copy.svg
actions/48/document-page-setup.svg
actions/48/edit-copy.svg

This adds some semi-transparent borders to a few icons that did not have them at certain sizes (mostly document actions). Should look a bit sharper with dark backgrounds.
---
Sorry, hope little things like this aren't too annoying!
Current:
Proposed:

Actions: Add some semi-transparent borders

---

devices/128/usb-receiver.svg
devices/16/usb-receiver.svg
devices/24/usb-receiver.svg
devices/32/usb-receiver.svg
devices/48/usb-receiver.svg
devices/64/usb-receiver.svg

This adds icons for the USB universal mouse/keyboard receiver, closing #1240 . The set uses `drive-removeable-media-usb` as a base.

Usb reciever

---

cursors/meson.build

Seems like we're now missing cursors in some GTK3 apps, so add back these symlinks for legacy cursor names

Cursors: re-add symlinks for legacy names

---

categories/32/preferences-desktop-applications.svg

Would close #1167 
Looks like 32x was using both a circular gradient, as well as base colors outside the current iteration of the brand palette (maybe an older iteration of the slate ramp I'm not aware of). This PR linearizes that gradient as well as correcting the color stops.

Categories: preferences-desktop-applications match gradients

---

actions/16/document-save-as.svg
actions/24/document-save-as.svg
actions/32/document-save-as.svg
actions/48/document-save-as.svg

Fixes #1168 
In context with save and open icons:

Actions: use folder for saveas

---

actions/32/system-lock-screen.svg
actions/32/system-log-out.svg
actions/32/system-reboot.svg
actions/32/system-shutdown.svg
actions/48/system-lock-screen.svg
actions/48/system-log-out.svg
actions/48/system-reboot.svg
actions/48/system-shutdown.svg

We did these in elementary-xfce, was wondering if you all would be interested in them?
The dark icons were a little close to disabled-button looking and adding color helps with that and makes them easier to see on dark backgrounds. Also reboot uses rounded arrow.
Questions:
1) Only 32px and 48px exist, do you all want 24px and 16px added?
2) ~`system-restart` and `system-suspend` are non-FDO names, remove these or think about it in another PR?~ Nevermind, after checking the code base these are uses in elementary.
3) We also did suspend and hibernate, and switch user if you all want them (none are FDO, but are commonly used) (also, suspend was a different design than current, didn't want to change it without asking):

Actions: Refresh and add color to session icons

---

actions/16/mail-send-receive.svg
actions/24/mail-send-receive.svg
actions/symbolic/mail-send-receive-symbolic.svg

Options here! I submitted here Option A. But when I went to adjust the arrow aspect ratio of the symbolic icon (which was a little narrow), realized it used longer arrow tails (Option C).
So, Option A is what I submitted, the arrow tail matches the ones used in `document-send` and `browser-download`. Option C, the arrow tail matches `go-up` and `go-down`. Options B and D are just variants.
Just let me know which one is best. Thanks!
Light:
Dark:

Actions: Add color mail-send-receive

---

data/icons.metainfo.xml.in
meson.build

I have only a slight clue as to what I'm doing lol

Release 8.1.0

---

places/16/start-here.svg
places/24/start-here.svg
places/32/start-here.svg
places/48/start-here.svg
places/symbolic/start-here-symbolic.svg

Add `start-here` as defined in the spec: https://specifications.freedesktop.org/icon-naming-spec/latest/#names
using a link to edit-find because that's what we use in the applications-menu by default

Places: add start-here

---

data/elementary.gpl

I proposed getting the palette shipped with [Inkscape](https://gitlab.com/inkscape/inkscape/-/tree/master/share/palettes?ref_type=heads) in #984 as a longer term solution, and this is a follow-up to make sure we're all prim and proper before pursuing any such merge requests.

Prep palette file for Inkscape

---

index.theme.in

Currently, if no fitting icon is found in elementary icon theme, gtk falls back to `hicolor`, as per the fd.o spec. With this PR, it will first try to find missing icon in Adwaita (which is present in elementary OS) before resorting to displaying a missing icon image. This issue mainly affects GNOME Circle apps that heavily rely on Adwaita, and while it is recommended to bundle all non-fd.o icons, not all apps do so (unfortunately).
Before/after examples (Apostrophe and Ptyxis):

Use Adwaita as a fallback icon theme

---

actions/16/object-locked.svg
actions/16/object-unlocked.svg
actions/24/object-locked.svg
actions/24/object-unlocked.svg
actions/32/object-locked.svg
actions/32/object-unlocked.svg
actions/48/object-locked.svg
actions/48/object-unlocked.svg

As requested, I’m splitting #1369 into three pull requests. This first pull request adds the symlinks necessary for the Inkscape lock/unlock icons.

Add symlinks for Inkscape lock/unlock icons

---

actions/16/path-cut.svg
actions/16/path-flatten.svg
actions/16/path-fracture.svg
actions/16/path-split.svg
actions/24/path-cut.svg
actions/24/path-flatten.svg
actions/24/path-fracture.svg
actions/24/path-split.svg
actions/symbolic/path-cut-symbolic.svg
actions/symbolic/path-flatten-symbolic.svg
actions/symbolic/path-fracture-symbolic.svg
actions/symbolic/path-split-symbolic.svg

This pull request includes the `path-cut`, `path-flatten`, `path-fracture`and `path-split` icons used in the Inkscape Path menu, in 16px and 24px sizes as well as a symbolic version.
In the `path-cut` icon, the square is shown only as a stroke because Inkscape deletes the fill when the "Cut Path" menu item is selected. All other icons use filled shapes only.

Add missing mint-green path boolean operation Inkscape icons
