actions/128/edit-undo-rtl.svg, actions/128/edit-undo.svg, actions/16/edit-undo-rtl.svg, actions/16/edit-undo.svg, actions/24/edit-undo.svg, actions/32/edit-undo-rtl.svg, actions/48/edit-undo-rtl.svg, actions/64/edit-undo-rtl.svg, actions/64/edit-undo.svg
Uses semi-transparent stroke for edit-undo icons
fixes #14
=> add rtl variants for edit-undo

actions/128/edit-redo-rtl.svg, actions/16/edit-redo-rtl.svg, actions/16/edit-redo.svg, actions/24/edit-redo-rtl.svg, actions/24/edit-redo.svg, actions/32/edit-redo-rtl.svg, actions/32/edit-redo.svg, actions/48/edit-redo-rtl.svg, actions/64/edit-redo-rtl.svg
Use new green and semi-transparent strokes
add rtl icons
fixes #16
=> add rtl variants for edit-redo

actions/128/edit-select-all.svg, actions/16/edit-select-all.svg, actions/24/edit-select-all.svg, actions/32/edit-select-all.svg, actions/64/edit-select-all.svg
=> edit-select-all for all sizes

README.md, pre-commit
added a script for convenience.
fixes #36
=> added git pre-commit hook

mimes/128/application-javascript.svg, mimes/128/application-x-php.svg, mimes/128/text-css.svg, mimes/128/text-html.svg, mimes/24/application-vnd.oasis.opendocument.text-web.svg, mimes/24/application-x-class-file.svg, mimes/24/application-x-java.svg, mimes/24/application-xml.svg, mimes/24/html.svg, mimes/24/text-html.svg, mimes/24/text-htmlh.svg, mimes/24/text-x-java-source.svg, mimes/24/text-x-java.svg, mimes/24/text-xml.svg, mimes/24/www.svg, mimes/32/application-javascript.svg, mimes/32/application-x-php.svg, mimes/32/text-css.svg, mimes/32/text-html.svg, mimes/48/application-javascript.svg, mimes/48/application-x-javascript.svg, mimes/48/application-x-php.svg, mimes/48/text-css.svg, mimes/48/text-html.svg, mimes/64/application-javascript.svg, mimes/64/application-x-php.svg, mimes/64/text-css.svg, mimes/64/text-html.svg
Redo web mimes:
* JS: application-javascript
* HTML: text-html
* CSS: text-css
* PHP: application-x-php
Fixes #69
=> Redo web mimes

devices/128/input-tablet.svg, devices/16/camera-video.svg, devices/16/input-gaming.svg, devices/16/input-tablet.svg, devices/24/input-gaming.svg, devices/24/input-tablet.svg, devices/32/input-gaming.svg, devices/32/input-tablet.svg, devices/48/input-gaming.svg, devices/48/input-tablet.svg, devices/64/input-tablet.svg
Added input-tablet & input-gaming icons
Fixes #42 and #40
=> Input icons

apps/128/applets-screenshooter.svg, apps/32/applets-screenshooter.svg, apps/48/applets-screenshooter.svg, apps/64/applets-screenshooter.svg
We don't use this anymore right?
=> remove applets screenshooter

categories/32/preferences-system-network.svg, categories/48/preferences-system-network.svg, categories/64/preferences-system-network.svg, status/32/network-error.svg, status/48/network-error.svg, status/48/network-idle.svg, status/64/network-error.svg
Make them look less like a bunch of electrons.
=> Update Network icons

categories/128/preferences-system-network.svg, categories/16/preferences-system-network.svg, categories/24/preferences-system-network.svg, categories/32/preferences-system-network.svg, categories/48/preferences-system-network.svg, categories/64/preferences-system-network.svg, places/128/network-workgroup.svg, places/16/network-workgroup.svg, places/24/network-workgroup.svg, places/32/network-workgroup.svg, places/48/network-workgroup.svg, places/64/network-workgroup.svg
Adds missing `preferences-system-network` icons, which are then used as a symlink for `network-workgroup` closes #87
=> Added preferences-network icons; symlinked network-workgroup

status/48/media-playlist-repeat.svg
The stroke was a bit light compared to other icons, just a minor fix to make it match
=> improved outer stroke on playlist repeat icon

places/24/folder-pictures.svg
New 24px folder-pictures icon to match the style of the 16px version.
=> update 24 folder-pictures to match 16

actions/24/pane-hide-symbolic-rtl.svg, actions/24/pane-hide-symbolic.svg, actions/24/pane-show-symbolic-rtl.svg, actions/24/pane-show-symbolic.svg
The 24px symbolic pane show/hide icons were a bit lacking, so I made 'em a bit nicer looking
=> less blocky pane show/hide icons

mimes/48/audio-x-generic.svg
=> restoring 48 audio-x-generic

status/48/notification-disabled.svg
=> improved notification-disabled contrast

status/symbolic/network-cellular-signal-excellent-secure-symbolic.svg, status/symbolic/network-cellular-signal-good-secure-symbolic.svg, status/symbolic/network-cellular-signal-none-secure-symbolic.svg, status/symbolic/network-cellular-signal-ok-secure-symbolic.svg, status/symbolic/network-cellular-signal-okay-symbolic.svg, status/symbolic/network-cellular-signal-weak-secure-symbolic.svg, status/symbolic/network-wired-secure-symbolic.svg, status/symbolic/network-wireless-signal-excellent-secure-symbolic.svg, status/symbolic/network-wireless-signal-good-secure-symbolic.svg, status/symbolic/network-wireless-signal-ok-secure-symbolic.svg, status/symbolic/network-wireless-signal-weak-secure-symbolic.svg, status/symbolic/nm-signal-0-secure-symbolic.svg, status/symbolic/nm-signal-0-symbolic.svg, status/symbolic/nm-signal-100-secure-symbolic.svg, status/symbolic/nm-signal-100-symbolic.svg, status/symbolic/nm-signal-25-secure-symbolic.svg, status/symbolic/nm-signal-25-symbolic.svg, status/symbolic/nm-signal-50-secure-symbolic.svg, status/symbolic/nm-signal-50-symbolic.svg, status/symbolic/nm-signal-75-secure-symbolic.svg, status/symbolic/nm-signal-75-symbolic.svg
=> Network icons

status/48/battery-full-charged.svg
The glow didn't really work out, so try something else
=> redo full-charged

devices/48/audio-speaker-center-back-testing.svg, devices/48/audio-speaker-center-back.svg, devices/48/audio-speaker-center-testing.svg, devices/48/audio-speaker-center.svg, devices/48/audio-speaker-left-back-testing.svg, devices/48/audio-speaker-left-back.svg, devices/48/audio-speaker-left-side-testing.svg, devices/48/audio-speaker-left-side.svg, devices/48/audio-speaker-left-testing.svg, devices/48/audio-speaker-left.svg, devices/48/audio-speaker-right-back-testing.svg, devices/48/audio-speaker-right-back.svg, devices/48/audio-speaker-right-side-testing.svg, devices/48/audio-speaker-right-side.svg, devices/48/audio-speaker-right-testing.svg, devices/48/audio-speaker-right.svg, devices/48/audio-speaker-testing.svg, devices/48/audio-subwoofer-testing.svg, devices/48/audio-subwoofer.svg
=> added audio-testing icons

apps/16/system-os-install.svg, apps/16/ubiquity.svg, apps/24/system-os-install.svg, apps/24/ubiquity.svg
Did these sizes for Ubuntu MATE, so here they are for elementary :)
=> add 16px and 24px installer

status/24/battery-caution-symbolic.svg, status/24/battery-empty-symbolic.svg, status/symbolic/battery-caution-symbolic.svg, status/symbolic/battery-empty-symbolic.svg
Also make sure to sync up the 24px variants
=> add background to empty symbolic battery icons for more presence

status/24/battery-missing-symbolic.svg, status/symbolic/channel-insecure-symbolic.svg, status/symbolic/security-low-symbolic.svg
=> Replace open locks with slashie locks

apps/48/system-software-install.svg
This makes the square portion of the icon match other icons at this size
=> Make AppCenter icon fill the canvas at 48px

actions/128/insert-link.svg, actions/128/insert-object.svg, actions/32/insert-link.svg, actions/48/insert-link.svg, actions/64/insert-link.svg
Closes #171 
I opted for the a symbolic version on the circle for the larger sizes to better fill the canvas.
=> Insert link

mimes/16/text-csv-rtl.svg, mimes/16/text-csv.svg, mimes/24/text-csv-rtl.svg, mimes/24/text-csv.svg, mimes/32/text-csv-rtl.svg, mimes/32/text-csv.svg, mimes/48/text-csv-rtl.svg, mimes/48/text-csv.svg, mimes/64/text-csv-rtl.svg, mimes/64/text-csv.svg
=> add symlinks for text-csv

categories/48/preferences-desktop-display.svg
=> Add 48px preferences-desktop-display

status/24/notification-disabled-symbolic.svg, status/symbolic/channel-insecure-symbolic.svg, status/symbolic/security-low-symbolic.svg
=> All slashies now go NW/SE

mimes/48/text-x-changelog.svg, mimes/48/text-x-patch.svg, mimes/64/text-x-changelog.svg, mimes/64/text-x-patch.svg
Featuring colors from our new neato palette shades thingy
=> make changelog mime flat, symlink patch

mimes/128/text-x-copying-rtl.svg, mimes/128/text-x-copying.svg, mimes/16/text-x-copying.svg, mimes/24/text-x-copying-rtl.svg, mimes/24/text-x-copying.svg, mimes/32/text-x-copying-rtl.svg, mimes/32/text-x-copying.svg, mimes/48/text-x-copying-rtl.svg, mimes/48/text-x-copying.svg, mimes/64/text-x-copying-rtl.svg, mimes/64/text-x-copying.svg, mimes/symbolic/text-x-copying-symbolic.svg
=> Text copying

categories/128/system-help.svg, categories/16/system-help.svg, categories/24/system-help.svg, categories/32/system-help.svg, categories/64/system-help.svg
system-help is in the spec, so symlink it
=> Symlink system-help

devices/64/input-keyboard.svg
Hi, I re-did the keyboard icon for 64px for elementary-xfce, thought I should push it upstream.
=> Add 64px version of keyboard

mimes/128/text-css.svg, mimes/16/text-css.svg, mimes/24/text-css.svg, mimes/32/text-css.svg, mimes/48/text-css.svg, mimes/64/text-css.svg
Stole the symbol from the Code icon
=> text-css for all sizes, colors to new palette

status/symbolic/battery-caution-charging-symbolic.svg, status/symbolic/battery-caution-symbolic.svg, status/symbolic/battery-empty-charging-symbolic.svg, status/symbolic/battery-empty-symbolic.svg, status/symbolic/battery-full-charged-symbolic.svg, status/symbolic/battery-full-charging-symbolic.svg, status/symbolic/battery-full-symbolic.svg, status/symbolic/battery-good-charging-symbolic.svg, status/symbolic/battery-good-symbolic.svg, status/symbolic/battery-low-charging-symbolic.svg, status/symbolic/battery-low-symbolic.svg
=> updated battery icons

AUTHORS, CONTRIBUTORS
- put me back in CONTRIBUTORS but at #1 :wink:
=> accurate AUTHORS file

status/24/network-cellular-signal-excellent-secure-symbolic.svg, status/24/network-cellular-signal-good-secure-symbolic.svg, status/24/network-cellular-signal-none-secure-symbolic.svg, status/24/network-cellular-signal-ok-secure-symbolic.svg, status/24/network-cellular-signal-weak-secure-symbolic.svg
=> Add secure cellular icons

devices/32/network-cellular.svg, devices/48/network-cellular.svg
=> Add network-cellular to devices

status/16/dialog-error.svg, status/24/dialog-error.svg, status/32/dialog-error.svg, status/48/dialog-error.svg, status/64/dialog-error.svg
Also fixes size to be consistent with other circle icons
=> Redo dialog-error with new palette

actions/24/process-stop-symbolic.svg
Fixes #334 
Restores the old 24px process-stop-symbolic icon just to avoid breaking epiphany
=> 24 process stop symbolic

emblems/24/emblem-downloads.svg, emblems/24/emblem-synchronized.svg, places/24/folder-download.svg
Add a couple emblems that are in the fd.o spec
=> Add 24px emblems

mimes/128/application-vnd.cups-pdf-banner.svg, mimes/128/text-x-preview.svg, mimes/16/application-vnd.cups-pdf-banner.svg, mimes/16/text-x-preview.svg, mimes/24/application-vnd.cups-pdf-banner.svg, mimes/24/text-x-preview.svg, mimes/32/application-vnd.cups-pdf-banner.svg, mimes/32/text-x-preview.svg, mimes/48/application-vnd.cups-pdf-banner.svg, mimes/48/text-x-preview.svg, mimes/64/application-vnd.cups-pdf-banner.svg, mimes/64/text-x-preview.svg
Fixes #357 
Also vacuums text-x-preview because pre-commit hooks
=> Symlink printer test page mime

actions/48/mail-archive.svg
Scaled to 48px because 3rd party dev used this on a welcome screen
=> Scale mail archive icon to 48px

actions/48/system-reboot.svg
Shadow was on top of the glyph. oops
=> Fix a layering mistake in 48px reboot

actions/symbolic/align-horizontal-center-symbolic.svg, actions/symbolic/align-horizontal-left-symbolic-rtl.svg, actions/symbolic/align-horizontal-left-symbolic.svg, actions/symbolic/align-horizontal-right-symbolic-rtl.svg, actions/symbolic/align-horizontal-right-symbolic.svg, actions/symbolic/align-vertical-bottom-symbolic.svg, actions/symbolic/align-vertical-center-symbolic.svg, actions/symbolic/align-vertical-top-symbolic.svg
=> added align symbolic icons

actions/symbolic/edit-clear-symbolic-rtl.svg, actions/symbolic/edit-clear-symbolic.svg
=> Vertically center edit-clear-symbolic in entry

status/symbolic/process-error-symbolic.svg
Fixes a style issue pointed out in https://github.com/elementary/terminal/pull/168
=> Style process error to match process-completed

apps/48/internet-news-reader-symbolic.svg, apps/symbolic/internet-news-reader-symbolic.svg
=> Add symbolic news reader

categories/symbolic/emoji-food-symbolic.svg
=> emoji food category icon

categories/symbolic/emoji-nature-symbolic.svg
=> Emoji nature symbolic

devices/16/bluetooth.svg, devices/24/bluetooth.svg, devices/32/bluetooth.svg, devices/48/bluetooth.svg
Make sure we use only colors from the palette here, matches the gradient used in the blue circle icons like `preferences-desktop-accessibilty`
=> Use palette colors for bluetooth icons

mimes/128/text-x-gettext-translation.svg, mimes/16/text-x-gettext-translation-template.svg, mimes/16/text-x-gettext-translation.svg, mimes/24/text-x-gettext-translation-template.svg, mimes/24/text-x-gettext-translation.svg, mimes/32/text-x-gettext-translation-template.svg, mimes/32/text-x-gettext-translation.svg, mimes/48/text-x-gettext-translation-template.svg, mimes/48/text-x-gettext-translation.svg, mimes/64/text-x-gettext-translation-template.svg, mimes/64/text-x-gettext-translation.svg
=> Translation mimes

devices/128/computer-laptop.svg, devices/16/computer-laptop.svg, devices/24/computer-laptop.svg, devices/32/computer-laptop.svg, devices/48/computer-laptop.svg, devices/64/computer-laptop.svg
Also messed with some paths to help with better rendering at smaller sizes.
=> Fixed some stray nodes, colours, and transparencies

actions/128/contact-new.svg, actions/64/contact-new.svg
=> Remove mime style background on 64px & 128px contact-new icons

devices/128/phone.svg, devices/24/phone.svg, devices/64/phone.svg
=> Add missing phone sizes

status/64/security-high.svg, status/64/security-low.svg, status/64/security-medium.svg
Used colors from our new palette and made the borders shiny, plus symbols
=> do shiny things, add symbols

mimes/128/text-x-csrc.svg, mimes/32/text-x-csrc.svg, mimes/48/text-x-csrc.svg, mimes/64/text-x-csrc.svg
These are still kinda fucky in terms of sizing and placement and stuff but at least they're more consistent :man_shrugging:
=> flatten C mimes

README.md, elementary.gpl
Also copies the directions for the palette file from CONTRIBUTING.md
=> Add Leather to palette

apps/128/internet-news-reader.svg, apps/128/multimedia-audio-player.svg, apps/128/system-software-update.svg, apps/16/internet-news-reader.svg, apps/16/multimedia-audio-player.svg, apps/16/system-software-update.svg, apps/24/internet-news-reader.svg, apps/24/multimedia-audio-player.svg, apps/24/system-software-update.svg, apps/32/internet-news-reader.svg, apps/32/multimedia-audio-player.svg, apps/32/system-software-update.svg, apps/48/internet-news-reader.svg, apps/48/multimedia-audio-player.svg, apps/48/system-software-update.svg, apps/64/internet-news-reader.svg, apps/64/multimedia-audio-player.svg, apps/64/system-software-update.svg
Update all of the orange tile apps to use colors from the new palette
=> Orange tile apps to new palette

apps/128/system-software-install.svg, apps/16/system-software-install.svg, apps/24/system-software-install.svg, apps/32/system-software-install.svg, apps/48/system-software-install.svg, apps/64/system-software-install.svg
This matches the new developer branding.
I also used blueberry for the window to brighten it up a bit.
=> Use Grape 700 in appcenter icon

categories/32/preferences-system-windows.svg
=> Add 32px preferences-system-windows

categories/32/applications-multimedia.svg, categories/32/preferences-desktop-accessibility-zoom.svg, categories/32/preferences-desktop-wallpaper.svg, categories/48/applications-multimedia.svg, categories/64/preferences-desktop-wallpaper.svg
So we don't have 3 different blues going on in keyboard shortcut settings
=> Use palette blue in category icons

places/symbolic/tag-symbolic.svg
=> Add symbolic tag

categories/symbolic/preferences-system-symbolic.svg
=> Symlink preferences system back to open menu

status/48/notification-disabled.svg
=> Flip notification disabled and use colors from palette

apps/128/postscript-viewer.svg, apps/16/postscript-viewer.svg, apps/24/postscript-viewer.svg, apps/32/postscript-viewer.svg, apps/48/postscript-viewer.svg, apps/64/postscript-viewer.svg
Uses the new red from the palette
=> Use new red in Evince

places/16/folder-download.svg, places/24/folder-download.svg
=> Make the downloads icon green

categories/32/preferences-desktop-keyboard.svg, categories/48/preferences-desktop-keyboard.svg, categories/64/preferences-desktop-keyboard.svg
Fixes #460 
While we're here, let's use palette colors
=> add 64px keyboard prefs

places/16/folder-videos.svg, places/24/folder-videos.svg
Matches the colors in the small places/folder-videos icons to categories/applications-multimedia
=> Match small folder-videos to applications-multimedia

actions/symbolic/process-stop-symbolic.svg, status/128/process-completed.svg
Matches better with the non-symbolic version imo
=> Make process-stop a solid icon

status/32/dialog-password.svg, status/32/gtk-dialog-authentication.svg
So it can be overlaid in dialogs
=> Add 32px dialog password

devices/48/printer-symbolic.svg, devices/symbolic/printer-symbolic.svg
Fixes a problem where printer notifications had a grey box behind them
=> Remove artifact behind printer-symbolic

actions/16/document-properties.svg, actions/24/document-properties.svg, actions/32/document-properties.svg, actions/48/document-properties.svg, actions/64/document-properties.svg, actions/symbolic/document-properties-symbolic.svg
=> Make document properties into a wrench

mimes/128/application-vnd.oasis.opendocument.chart.svg, mimes/16/application-vnd.oasis.opendocument.chart.svg, mimes/24/application-vnd.oasis.opendocument.chart.svg, mimes/32/application-vnd.oasis.opendocument.chart.svg, mimes/48/application-vnd.oasis.opendocument.chart.svg, mimes/64/application-vnd.oasis.opendocument.chart.svg
Add missing sizes and use palette colors
=> Make chart mimes consistent

mimes/128/text-x-install.svg, mimes/16/text-x-install.svg, mimes/24/text-x-install.svg, mimes/32/text-x-install.svg, mimes/48/text-x-install.svg, mimes/64/text-x-install.svg
Fixes #487 
Use silver 700 for better contrast
=> Make text-x-install consistent

categories/16/preferences-desktop-locale.svg
=> Update 16px prefs-desktop-locale

mimes/128/text-x-chdr.svg, mimes/16/text-x-chdr.svg, mimes/24/text-x-chdr.svg, mimes/32/text-x-chdr.svg, mimes/48/text-x-chdr.svg, mimes/64/text-x-chdr.svg
Fixes #488 
And add missing sizes
=> Make chdr mime consistent

categories/48/applications-webbrowsers.svg
Fixes #504 
Not a real category :grimacing:
=> remove applications-webbrowsers

devices/24/battery.svg, devices/32/battery.svg, status/32/battery-full-charged.svg
Fixes #506 
Fixes #507 
* Added `devices/32/battery`
* Added `status/32/battery-full-charged`
* Changed `status/32/battery-full` and `status/32/battery-full-charging` to blue
* Changed`devices/24/battery` to match others
=> Batteries included

mimes/24/package-x-generic.svg, mimes/32/package-x-generic.svg
Get it? Cuz they're cardboard boxes and CSS :sunglasses:
=> Fix box-shadows

status/32/printer-error.svg, status/48/network-wired-disconnected.svg
=> Add a couple error state icons

mimes/128/model.svg, mimes/16/model.svg, mimes/24/model.svg, mimes/32/model.svg, mimes/48/model.svg, mimes/64/model.svg
=> more consistent model icons

mimes/128/text-x-csrc.svg, mimes/16/text-x-csrc.svg, mimes/24/text-x-csrc.svg, mimes/32/text-x-csrc.svg, mimes/48/text-x-csrc.svg, mimes/64/text-x-csrc.svg
Fixes #532 
Based on https://commons.wikimedia.org/wiki/File:The_C_Programming_Language_logo.svg
=> Redo C mime

mimes/128/application-x-subrip.svg, mimes/128/text-x-ssa.svg, mimes/16/application-x-subrip.svg, mimes/16/text-x-ssa.svg, mimes/24/application-x-subrip.svg, mimes/24/text-x-ssa.svg, mimes/32/application-x-subrip.svg, mimes/32/text-x-ssa.svg
=> mimes: text-x-ssa missing sizes

meson/symlink.py
=> Use the right destination prefix for symlinks

actions/128/event-new.svg, actions/16/event-new.svg, actions/32/event-new.svg, actions/48/event-new.svg, actions/64/event-new.svg
Adds missing sizes for the action event-new
=> Add sizes for event-new

mimes/128/text-x-bibtex.svg, mimes/16/text-x-bibtex.svg, mimes/24/text-x-bibtex.svg, mimes/32/text-x-bibtex.svg, mimes/48/text-x-bibtex.svg, mimes/64/text-x-bibtex.svg
Closes https://github.com/elementary/icons/issues/568
=> mimes: add text-x-bibtex

apps/24/accessories-character-map.svg, apps/32/accessories-character-map.svg, apps/48/accessories-character-map.svg, apps/64/accessories-character-map.svg, categories/24/preferences-desktop-keyboard.svg, categories/32/preferences-desktop-keyboard.svg, categories/48/preferences-desktop-keyboard.svg, categories/64/preferences-desktop-keyboard.svg
Steal some free fd.o spec compliance with a symlink
=> Link prefs keyboard to charmap

categories/24/preferences-system-sharing.svg, emblems/24/emblem-shared.svg
=> Add symlink for emblem-shared

status/16/changes-prevent.svg, status/24/changes-allow.svg, status/24/changes-prevent.svg, status/24/locked.svg, status/32/changes-allow.svg, status/32/changes-prevent.svg, status/32/locked.svg
=> Add changes allow/prevent

mimes/128/x-office-document-rtl.svg, mimes/128/x-office-document-template-rtl.svg, mimes/128/x-office-document-template.svg, mimes/128/x-office-document.svg, mimes/16/x-office-document-rtl.svg, mimes/16/x-office-document-template-rtl.svg, mimes/16/x-office-document-template.svg, mimes/16/x-office-document.svg, mimes/24/x-office-document-rtl.svg, mimes/24/x-office-document-template-rtl.svg, mimes/24/x-office-document-template.svg, mimes/24/x-office-document.svg, mimes/32/x-office-document-rtl.svg, mimes/32/x-office-document-template-rtl.svg, mimes/32/x-office-document-template.svg, mimes/32/x-office-document.svg, mimes/48/x-office-document-rtl.svg, mimes/48/x-office-document-template-rtl.svg, mimes/48/x-office-document-template.svg, mimes/48/x-office-document.svg, mimes/64/x-office-document-rtl.svg, mimes/64/x-office-document-template-rtl.svg, mimes/64/x-office-document-template.svg, mimes/64/x-office-document.svg
And actually flip the stripe's side for RTL
=> x-office-document in new palette colors

mimes/16/application-pgp.svg, mimes/24/application-pgp.svg, mimes/48/application-pgp.svg
=> mimes: added missing application-pgp

mimes/128/x-office-presentation-rtl.svg, mimes/128/x-office-presentation-template-rtl.svg, mimes/128/x-office-presentation-template.svg, mimes/128/x-office-presentation.svg, mimes/16/x-office-presentation-rtl.svg, mimes/16/x-office-presentation-template-rtl.svg, mimes/16/x-office-presentation-template.svg, mimes/16/x-office-presentation.svg, mimes/24/x-office-presentation-rtl.svg, mimes/24/x-office-presentation-template-rtl.svg, mimes/24/x-office-presentation-template.svg, mimes/24/x-office-presentation.svg, mimes/32/x-office-presentation-rtl.svg, mimes/32/x-office-presentation-template-rtl.svg, mimes/32/x-office-presentation-template.svg, mimes/32/x-office-presentation.svg, mimes/48/x-office-presentation-rtl.svg, mimes/48/x-office-presentation-template-rtl.svg, mimes/48/x-office-presentation-template.svg, mimes/48/x-office-presentation.svg, mimes/64/x-office-presentation-rtl.svg, mimes/64/x-office-presentation-template-rtl.svg, mimes/64/x-office-presentation-template.svg, mimes/64/x-office-presentation.svg
And actually flip the stripe's side for RTL
=> x-office-presentation in new palette colors

places/32/folder-download.svg, places/32/folder-music-open.svg, places/32/folder-music.svg, places/32/folder-pictures-open.svg, places/32/folder-pictures.svg, places/32/folder-publicshare.svg, places/32/folder-recent.svg, places/32/folder-templates-open.svg, places/32/folder-templates.svg, places/32/folder-videos-open.svg, places/32/folder-videos.svg
Makes the glyphs on the 32px folder icons look a bit nicer (and more proportionate to their 64px counterparts)
=> Better 32px folder glyphs

status/24/dialog-password.svg, status/32/dialog-password.svg, status/48/dialog-password.svg, status/64/dialog-password.svg
=> Dialog password redesign

mimes/128/application-vnd.flatpak.ref.svg, mimes/16/application-vnd.flatpak.ref.svg, mimes/24/application-vnd.flatpak.ref.svg, mimes/32/application-vnd.flatpak.ref.svg, mimes/48/application-vnd.flatpak.ref.svg, mimes/64/application-vnd.flatpak.ref.svg
=> Add flatpak mime

status/48/notification-network-ethernet-disconnected.svg
=> Add network ethernet disconnected notification

devices/24/network-vpn.svg, devices/32/network-vpn.svg, devices/48/network-vpn.svg, devices/64/network-vpn.svg
Instead of recycling the lock, create a new icon based on the new security icons
=> Create specialized VPN icons

devices/64/bluetooth.svg
Pulled in the new bluetooth icons and noticed that the 64px size wasn't included, so I drew it up.
=> Add 64px bluetooth icon

actions/symbolic/tools-timer-symbolic.svg
Made this for Camera but could be useful for other apps
=> Add symbolic timer

mimes/128/aplication-x-partial-download.svg, mimes/16/aplication-x-partial-download.svg, mimes/24/aplication-x-partial-download.svg, mimes/32/aplication-x-partial-download.svg, mimes/48/aplication-x-partial-download.svg, mimes/64/aplication-x-partial-download.svg
=> application-x-partial-download

devices/symbolic/camera-video-symbolic.svg
=> Symlink view-list-video-symbolic to camera-video-symbolic

places/symbolic/playlist-queue-symbolic.svg, places/symbolic/playlist-symbolic.svg
=> Add symbolic icons for playlist and playlist-queue

status/symbolic/input-keyboard-capslock-symbolic.svg
Goes with https://github.com/elementary/greeter/pull/196
=> Add symbolic capslock icon

devices/128/phone.svg, devices/16/phone.svg, devices/24/phone.svg, devices/32/phone.svg, devices/48/phone.svg, devices/64/phone.svg
because phones look a bit different these days
=> Redesign Phone icons

actions/symbolic/mail-send-symbolic-rtl.svg, categories/24/preferences-system-notifications-rtl.svg, categories/32/preferences-system-notifications-rtl.svg
=> Add RTL icons

devices/128/computer-convertible.svg, devices/16/computer-convertible.svg, devices/24/computer-convertible.svg, devices/32/computer-convertible.svg, devices/48/computer-convertible.svg, devices/64/computer-convertible.svg
=> Add computer-convertible symlinks

actions/16/edit-flag.svg, actions/24/edit-flag.svg, actions/24/edit-mark.svg
=> edit-flag: new palette colors

places/128/user-desktop-open.svg, places/16/user-desktop-open.svg, places/24/user-desktop-open.svg, places/32/user-desktop-open.svg, places/48/user-desktop-open.svg, places/64/user-desktop-open.svg
=> Add a symlink for user-desktop-open

devices/128/drive-harddisk-solidstate.svg, devices/16/drive-harddisk-solidstate.svg, devices/24/drive-harddisk-solidstate.svg, devices/32/drive-harddisk-solidstate.svg, devices/48/drive-harddisk-solidstate.svg, devices/64/drive-harddisk-solidstate.svg
Made icons for SSD devices.
Fixes #458.
Looks like this:
=> New SSD iconset

status/symbolic/input-keyboard-numlock-symbolic.svg
Goes with https://github.com/elementary/greeter/pull/219/files
=> Add numlock icon

actions/16/align-horizontal-center.svg, actions/16/align-horizontal-left.svg, actions/16/align-horizontal-right.svg, actions/16/align-vertical-bottom.svg, actions/16/align-vertical-center.svg, actions/16/align-vertical-top.svg
I think this is better than the way Tango scaled these
=>  Proportion scaling for 16px align actions

actions/16/distribute-horizontal-center.svg, actions/16/distribute-horizontal-gaps.svg, actions/16/distribute-horizontal-left.svg, actions/16/distribute-horizontal-right.svg, actions/16/distribute-vertical-center.svg, actions/16/distribute-vertical-gaps.svg, actions/16/distribute-vertical-top.svg, actions/24/distribute-horizontal-center.svg, actions/24/distribute-horizontal-gaps.svg, actions/24/distribute-horizontal-left.svg, actions/24/distribute-horizontal-right.svg, actions/24/distribute-vertical-bottom.svg, actions/24/distribute-vertical-center.svg, actions/24/distribute-vertical-gaps.svg, actions/24/distribute-vertical-top.svg
=> 16px and 24px distribute actions

devices/symbolic/media-memory-sembolic.svg
=> media-memory-symbolic

mimes/symbolic/application-x-firmware-symbolic.svg
=> application-x-firmware-symbolic

status/64/night-light.svg
=> Add 64px nightlight icon

status/128/image-missing.svg, status/16/image-missing.svg, status/24/image-missing.svg, status/32/image-missing.svg, status/48/image-missing.svg, status/64/image-missing.svg
Makes it a lot less aggressive as a placeholder
=> Simplify image-missing

devices/symbolic/computer-convertible-symbolic.svg, devices/symbolic/computer-laptop-symbolic.svg
=> computer-laptop-symbolic

apps/16/system-software-update.svg, apps/24/system-software-update.svg, apps/32/system-software-update.svg, apps/48/system-software-update.svg, apps/64/system-software-update.svg
Something a little more exciting :)
Context:
=> Change shape of system-software-update

status/32/network-wireless-signal-excellent.svg, status/32/network-wireless-signal-good.svg, status/32/network-wireless-signal-ok.svg, status/32/network-wireless-signal-weak.svg
=> Add 32px wireless signal icons

status/16/user-available.svg, status/16/user-away.svg, status/16/user-offline.svg, status/24/user-available.svg, status/24/user-away.svg, status/24/user-busy.svg, status/24/user-offline.svg
I wanna use these in the VPN dialog:
=> Add 24px user status icons

actions/64/view-reader.svg, actions/symbolic/view-reader-symbolic.svg
=> view-reader fix

mimes/24/extension.svg, mimes/32/extension.svg, mimes/48/extension.svg, mimes/64/extension.svg
=> Remove bottom stroke of top circles in the extension icon

status/48/network-wireless-signal-excellent.svg, status/48/network-wireless-signal-good.svg, status/48/network-wireless-signal-ok.svg, status/48/network-wireless-signal-weak.svg
For future use in network settings
=> Add 48px network wireless signal

cursors/24/zoom-in.svg, cursors/24/zoom-out.svg, cursors/meson.build, cursors/zoom-in.in, cursors/zoom-out.in, data/icons.appdata.xml.in
=> Add zoom cursors

cursors/24/no-drop.svg, cursors/meson.build, cursors/no-drop.in, data/icons.appdata.xml.in
=> Add no drop cursor

cursors/24/all-scroll.svg, cursors/all-scroll.in, cursors/meson.build, data/icons.appdata.xml.in
=> Add all-scroll cursor

actions/24/window-close-symbolic.svg
=> Add 24px window-close-symbolic

README.md
Fixes #868 by updating the link
=> README: Fix link to palette

apps/48/apport.svg, apps/64/apport.svg
I don't think we want to make apport look more native
=> Remove apport symlink

data/elementary.gpl
=> bubblegum palette

actions/24/draw-eraser.svg
It's a super small change but it now uses all palette colors.
=> Eraser stroke to palette color

actions/16/document-edit.svg, actions/24/document-edit.svg, actions/24/edit-find-replace.svg, actions/24/mail-message-new.svg, actions/48/document-edit.svg, actions/48/edit-find-replace.svg, apps/128/accessories-text-editor.svg, apps/16/accessories-text-editor.svg, apps/24/accessories-text-editor.svg, apps/32/accessories-text-editor.svg, apps/48/accessories-text-editor.svg, apps/64/accessories-text-editor.svg, data/icons.appdata.xml.in
This makes for higher contrast against dark background if/when dark preference happens.
=> Yellow pencils

data/icons.appdata.xml.in, meson.build
Needed for new AppCenter loading view
=> Release 5.3.0

.github/workflows/main.yml, cursors/meson.build
=> Use librsvg instead of inkscape

data/icons.appdata.xml.in, meson.build
To fix builds downstream with the Inkscape 1.0 CLI API break.
=> Release 5.3.1

apps/16/internet-mail.svg, apps/32/internet-mail.svg
Seems that both are using the old geary style
=> Use clean style for internet-mail in 16 and 32px

cursors/meson.build
As specified by the CSS specification https://developer.mozilla.org/fr/docs/Web/CSS/cursor
=> cursors: Add symlink for cell and grab pointers

mimes/128/application-json.svg, mimes/16/application-json.svg, mimes/24/application-json.svg, mimes/32/application-json.svg, mimes/48/application-json.svg, mimes/64/application-json.svg
Closes https://github.com/elementary/icons/issues/623
=> mimes: add application-json mime

actions/24/tool-spray.svg
Fixes #715 
This is how the icon look in elementary's light theme
This is how the icon look in elementary's dark theme
There is another layer where some of the unused ideas and assets used in the process of designing this icon is stored. I will be cleaning them up once it's finalized and approved.
=> Add Inkscape Spray Can Tool

apps/symbolic/office-task-symbolic.svg
=> office-task-symbolic

status/32/battery-caution-charging.svg, status/32/battery-caution.svg, status/32/battery-empty-charging.svg, status/32/battery-empty.svg, status/32/battery-full-charging.svg, status/32/battery-full.svg, status/32/battery-good-charging.svg, status/32/battery-good.svg, status/32/battery-low-charging.svg, status/32/battery-low.svg, status/48/battery-ac-adapter.svg, status/48/battery-caution-charging.svg, status/48/battery-caution.svg, status/48/battery-empty-charging.svg, status/48/battery-empty.svg, status/48/battery-full-charging.svg, status/48/battery-good-charging.svg, status/48/battery-good.svg, status/48/battery-low-charging.svg, status/48/battery-low.svg
=> Color battery reflections

categories/32/preferences-system-power.svg, categories/48/preferences-system-power.svg, status/32/battery-caution-charging.svg, status/32/battery-empty-charging.svg, status/32/battery-full-charging.svg, status/32/battery-good-charging.svg, status/32/battery-low-charging.svg, status/48/battery-ac-adapter.svg, status/48/battery-caution-charging.svg, status/48/battery-empty-charging.svg, status/48/battery-full-charging.svg, status/48/battery-good-charging.svg, status/48/battery-low-charging.svg
battery-ac-adapter
battery-caution-charging
battery-empty-charging
battery-full-charging
battery-good-charging
battery-low-charging
preferences-system-power
=> Make lightning shape consistent

actions/24/media-skip-backward-symbolic-rtl.svg, actions/24/media-skip-backward-symbolic.svg, actions/24/media-skip-forward-symbolic-rtl.svg, actions/24/media-skip-forward-symbolic.svg, actions/symbolic/media-skip-backward-symbolic-rtl.svg, actions/symbolic/media-skip-backward-symbolic.svg, actions/symbolic/media-skip-forward-symbolic-rtl.svg, actions/symbolic/media-skip-forward-symbolic.svg
=> media skip symbolics

categories/48/applications-accessories.svg
This uses red for the scissors to match the screenshot icon and used a more wood color for the ruler instead of yellow.
=> Better contrast for applications-accessories in dark styles

status/32/network-wireless-signal-good.svg, status/32/network-wireless-signal-ok.svg, status/32/network-wireless-signal-weak.svg, status/48/network-wireless-signal-good.svg, status/48/network-wireless-signal-ok.svg, status/48/network-wireless-signal-weak.svg
=> Improve empty space in wireless signal

actions/16/list-add.svg, actions/16/list-remove.svg, actions/24/list-add.svg, actions/24/list-remove.svg, actions/32/list-add.svg, actions/32/list-remove.svg, actions/48/list-add.svg, actions/48/list-remove.svg
=> Redo list-add and list-remove

actions/32/system-log-out.svg, actions/48/system-log-out.svg
=> Use new arrow shape in system-log-out

status/32/battery-good-charging.svg, status/32/battery-low-charging.svg, status/48/battery-good-charging.svg, status/48/battery-low-charging.svg
This ends up looking a little nicer in the indicator to my eye
=> Battery-charging: only color filled part of bolt

emblems/16/emblem-disabled.svg, emblems/16/emblem-enabled.svg, emblems/16/emblem-error.svg, emblems/16/emblem-mixed.svg, emblems/16/emblem-warning.svg, emblems/24/emblem-disabled.svg, emblems/24/emblem-enabled.svg, emblems/24/emblem-error.svg, emblems/24/emblem-mixed.svg, emblems/24/emblem-warning.svg
Fixes #827 
For now I've just copied the existing emblems. But in the future I imagine we'll do a better job differentiating them
=> Add status emblems

actions/16/edit-redo-rtl.svg, actions/16/edit-redo.svg, actions/16/edit-undo-rtl.svg, actions/16/edit-undo.svg, actions/24/edit-redo-rtl.svg, actions/24/edit-redo.svg, actions/24/edit-undo-rtl.svg, actions/24/edit-undo.svg, actions/32/edit-redo-rtl.svg, actions/32/edit-redo.svg, actions/32/edit-undo-rtl.svg, actions/32/edit-undo.svg, actions/48/edit-redo-rtl.svg, actions/48/edit-redo.svg, actions/48/edit-undo-rtl.svg, actions/48/edit-undo.svg, actions/symbolic/edit-redo-symbolic.svg, actions/symbolic/edit-undo-symbolic.svg
=> Use new arrow style for undo and redo

status/symbolic/software-update-available-symbolic.svg, status/symbolic/software-update-urgent-symbolic.svg
=> Update symbolic software update

categories/24/preferences-system-power-symbolic.svg
Trying to do something that looks better on desktop. I dunno. Drafting for thoughts
=> Update symbolic power prefs

devices/32/thunderbolt.svg
=> Add 32px devices/thunderbolt

status/16/process-error.svg, status/24/process-error.svg, status/32/process-error.svg, status/48/process-error.svg, status/64/process-error.svg
=> Status: Add color process-error

data/icons.appdata.xml.in
What the title says :)
Follow-up of #1035.
=> Fix two typos in icons.appdata.xml.in

data/icons.appdata.xml.in, places/16/playlist-queue.svg, places/48/playlist-queue.svg
I wanted to use a 48px version of this icon and then I realized there wasn't one
=> Add 48px playlist-queue

places/24/playlist-queue.svg
Turns out I want this in 24px too
=> Places: Add 24px playlist-queue

mimes/128/package-x-generic.svg, mimes/16/package-x-generic.svg, mimes/24/package-x-generic.svg, mimes/32/package-x-generic.svg, mimes/48/package-x-generic.svg, mimes/64/package-x-generic.svg
Using @micahilbery's latte palette :)
=> Redesign package-x-generic

apps/128/system-software-update.svg, apps/16/system-software-update.svg, apps/24/system-software-update.svg, apps/32/system-software-update.svg, apps/48/system-software-update.svg, apps/64/system-software-update.svg, apps/symbolic/system-software-update-symbolic.svg, status/128/software-update-urgent.svg, status/16/software-update-urgent.svg, status/24/software-update-urgent.svg, status/32/software-update-urgent.svg, status/48/software-update-urgent.svg, status/64/software-update-urgent.svg, status/symbolic/software-update-urgent-symbolic.svg
This has annoyed the hell out of me. They're updates, not "down"dates
=> Invert updates arrow

data/icons.appdata.xml.in, meson.build
I don't think there's any other removals we really need. We can always make changes or additions mid-cycle
=> Release 7.0.0

apps/128/preferences-desktop.svg, apps/24/preferences-desktop.svg, apps/32/preferences-desktop.svg, apps/48/preferences-desktop.svg, apps/64/preferences-desktop.svg
Just `preferences-desktop` from #1076
Use the new rounded square shape, remove corner screws while we're here
=> preferences-desktop: round square, remove screws

status/64/night-light.svg
More interesting colors that are more in line with what the feature does and using the same symbolic as we later use in the panel
=> Redesign Night Light

categories/32/preferences-desktop-workspaces.svg, categories/48/preferences-desktop-workspaces.svg, categories/64/preferences-desktop-workspaces.svg, data/icons.appdata.xml.in
Use the new square format, make sure we have consistency throughout
=> Clean up prefs-desktop-workspaces

mimes/meson.build
Fixes missing icons as reported in #1091
=> FileTypes: Add symlinks for PGP files

categories/24/preferences-desktop-wallpaper.svg, categories/32/preferences-desktop-wallpaper.svg, categories/48/preferences-desktop-wallpaper.svg, categories/64/preferences-desktop-wallpaper.svg
I want to give this its own icon in a future version, but for now symlink so that we don't break anything that's relying on this icon name
=> Categories: symlink preferences-desktop-wallpaper

devices/symbolic/audio-subwoofer-symbolic.svg
=> Devices: add audio-subwoofer-symbolic

mimes/meson.build
This is the file type for web extensions
=> FileTypes: symlink extension to application-x-xpinstall

mimes/16/video-x-generic.svg
=> FileTypes: Add 16px video-x-generic

actions/24/document-export-symbolic-rtl.svg, actions/24/document-export-symbolic.svg, actions/24/document-import-symbolic-rtl.svg, actions/24/document-import-symbolic.svg, actions/24/object-merge.svg, actions/24/pane-hide-symbolic-rtl.svg, actions/24/pane-hide-symbolic.svg, actions/24/pane-show-symbolic-rtl.svg, actions/24/pane-show-symbolic.svg
- Document Import/Export
- Object Merge
- Pane Hide/Show
---
If these need to be split into separate PRs let me know, I thought this might be okay since it was just a few. Thanks.
=> Actions: Use rounded arrow on some 24px icons

actions/16/object-merge.svg, actions/16/object-rotate-left.svg, actions/16/object-rotate-right.svg, actions/24/object-rotate-left.svg, actions/24/object-rotate-right.svg, actions/48/object-rotate-left.svg, actions/48/object-rotate-right.svg
Also for object-merge at 16px (24px was done in last commit)
=> Actions: Use rounded arrow for object-rotate

mimes/meson.build
=> Filetypes: link application-x-java-archive to package-x-generic

cursors/24/left_ptr_watch_0001.svg, cursors/24/left_ptr_watch_0002.svg, cursors/24/left_ptr_watch_0003.svg, cursors/24/left_ptr_watch_0004.svg, cursors/24/left_ptr_watch_0005.svg, cursors/24/left_ptr_watch_0006.svg, cursors/24/left_ptr_watch_0007.svg, cursors/24/left_ptr_watch_0008.svg, cursors/24/watch_0001.svg, cursors/24/watch_0002.svg, cursors/24/watch_0003.svg, cursors/24/watch_0004.svg, cursors/24/watch_0005.svg, cursors/24/watch_0006.svg, cursors/24/watch_0007.svg, cursors/24/watch_0008.svg, cursors/24/watch_0009.svg, cursors/24/watch_0010.svg, cursors/24/watch_0011.svg, cursors/24/watch_0012.svg, cursors/24/watch_0013.svg, cursors/24/watch_0014.svg, cursors/24/watch_0015.svg, cursors/24/watch_0016.svg
Split of #1248 focusing on redesigning `watch` to better accommodate color.
=> Redesign watch to accommodate color

data/icons.metainfo.xml.in
https://github.com/elementary/icons/compare/7.3.1...main
=> 8.0 Release Notes

apps/16/accessories-character-map-rtl.svg, apps/16/accessories-character-map.svg, apps/24/accessories-character-map-rtl.svg, categories/16/preferences-desktop-keyboard-rtl.svg, categories/16/preferences-desktop-keyboard.svg
It is used in Inkscape for the Unicode Characters pane.
=> Add 16px preferences-desktop-keyboard/accessories-character-map

actions/16/dialog-objects.svg, actions/24/dialog-objects.svg
=> Add dialog-objects for Inkscape
